name: 'Main Branch & Release'

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI'
    uses: ./.github/workflows/callable-ci.yml
    with:
      run_lint: true
      run_build: true

  release:
    name: 'Release'
    needs: [ci]
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-and-install

      - name: Create Release Pull Request (if changesets exist)
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_vscode:
    name: 'Release VSCode Extension'
    needs: [ci, release]
    if: needs.release.outputs.has_changesets == 'false' && needs.ci.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-and-install

      - uses: ./.github/actions/release-vscode
        with:
          azure-pat: ${{ secrets.AZURE_VSCODE_PAT }}
          open-vsx-pat: ${{ secrets.OPEN_VSX_PAT }}
